spring.config.activate.on-profile=prod

spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}

spring.sql.init.mode=always
spring.flyway.clean-disabled=true

logging.level.root=WARN
server.port=8080

