spring.config.activate.on-profile=dev

spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

spring.sql.init.mode=always
spring.flyway.clean-disabled=false

logging.level.org.springframework.web=DEBUG
logging.level.com.slash=DEBUG

server.port=8080

