spring.config.activate.on-profile=staging

spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}

spring.sql.init.mode=always
spring.flyway.clean-disabled=true

logging.level.org.springframework.web=INFO
logging.level.com.slash=DEBUG

server.port=8080

